In [1]:
 import numpy as np

# Basics

In [25]:
a = np.array([1,2,3,4], dtype="int32")
print(a)

[1 2 3 4]


In [12]:
b = np.array([[9.9, 7.8, 3.4, 6.0], [3.4,6.8, 11.2, 55.0]])
print(b)

[[ 9.9  7.8  3.4  6. ]
 [ 3.4  6.8 11.2 55. ]]


In [13]:
#get dimension of array
a.ndim

1

In [15]:
# get shape
b.shape

(2, 4)

In [19]:
# get type
a.dtype

dtype('int16')

In [23]:
#get size in bytes
a.itemsize

4

In [27]:
#get total size in bytes
a.nbytes


16

In [29]:
#get no of elements in an array
a.size

4

# Accessing/Changing specific elements, rows, col, etc

In [30]:
a = np.array([[1,2,3,4,5,6,7,8], [44,33,22,11,55,66,77,88]])
print(a)

[[ 1  2  3  4  5  6  7  8]
 [44 33 22 11 55 66 77 88]]


In [32]:
#get speicific element [r,c]
print(a[1,3])
print(a[0,-2])

11
7


In [34]:
# Get a specific row only
print(a[0 , :])
print(a[1 , :])

[1 2 3 4 5 6 7 8]
[44 33 22 11 55 66 77 88]


In [35]:
# get specific column
print(a[:,2])

[ 3 22]


In [41]:
# [ start:end:step]
print(a[0, 1:6:2])
print(a[1, 2:-3:2])

[2 4 6]
[22 55]


In [42]:
#assigning values
a[1,2] = 9
print(a)

[[ 1  2  3  4  5  6  7  8]
 [44 33  9 11 55 66 77 88]]


In [45]:
#changing values of entire colunm
a[:, 4] = [222,111]
print(a)

[[  1   2   3   4 222   6   7   8]
 [ 44  33   9  11 111  66  77  88]]


# 3D array

In [48]:
a= np.array([[[1,2,3],[4,5,6]], [[7,8,9],[11,12,13]]])
print(a)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [11 12 13]]]


In [50]:
#GET specific element
print(a[0,0,1])
print(a[1,1,2])

2
13


In [51]:
#changing value
a[:,1,:] = [[10,10,10],[100,100,100]]
a

array([[[  1,   2,   3],
        [ 10,  10,  10]],

       [[  7,   8,   9],
        [100, 100, 100]]])

# Initializing different types of arrays

In [54]:
#All 0s array
#np.zeros((shape), dtype)
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [55]:
#All 1s array
np.ones((4,2), dtype="int32")

array([[1, 1],
       [1, 1],
       [1, 1],
       [1, 1]])

In [56]:
#Any other number
#np.full((shape), value, dtype)
np.full((2,2),99)

array([[99, 99],
       [99, 99]])

In [57]:
#any other number with the size of like any other array

a = np.array([[1,2,3,4,5,6,7,8], [44,33,22,11,55,66,77,88]])
np.full_like(a, 11)


array([[11, 11, 11, 11, 11, 11, 11, 11],
       [11, 11, 11, 11, 11, 11, 11, 11]])

In [62]:
#random decimal numbers
np.random.rand(3,3,3)

array([[[0.44073893, 0.28063162, 0.35687888],
        [0.05959926, 0.51809579, 0.17110265],
        [0.49651645, 0.00421228, 0.04468444]],

       [[0.98192695, 0.93893351, 0.7807831 ],
        [0.09135567, 0.57996464, 0.06923682],
        [0.14587584, 0.06932491, 0.26502699]],

       [[0.80306212, 0.00731041, 0.40348254],
        [0.7330418 , 0.07075515, 0.02645052],
        [0.10940585, 0.9651377 , 0.96238556]]])

In [67]:
# Random integer values
#np.random.randint(start,end,size=(a,b))|
np.random.randint(2,7, size=(3,3))

array([[4, 5, 6],
       [6, 3, 3],
       [5, 2, 3]])

In [126]:
# Identity matrix
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [73]:
# Repeat any array 
arr = np.array([[4,5,6,7]])
rep = np.repeat(arr,4)
print(rep)
print("----------------------------------")
rep2 = np.repeat(arr,4,axis=0)
print(rep2)

[4 4 4 4 5 5 5 5 6 6 6 6 7 7 7 7]
----------------------------------
[[4 5 6 7]
 [4 5 6 7]
 [4 5 6 7]
 [4 5 6 7]]


## Copying arrays be careful!!!

In [74]:
a = np.array([1,2,3,4])
b = a.copy()
b[1] = 20
print(a)
print(b)

[1 2 3 4]
[ 1 20  3  4]


# Mathematics

In [84]:
a = np.array([1,2,3,4])
a

array([1, 2, 3, 4])

In [81]:
a+3

array([4, 5, 6, 7])

In [83]:
a-2

array([-1,  0,  1,  2])

In [78]:
a*3

array([ 3,  6,  9, 12])

In [85]:
a/3

array([0.33333333, 0.66666667, 1.        , 1.33333333])

In [87]:
a**2

array([ 1,  4,  9, 16], dtype=int32)

In [86]:
b = np.array([11,22,33,44])
a*b

array([ 11,  44,  99, 176])

In [88]:
#Taking sin 
np.sin(a)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

In [89]:
np.cos(a)

array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362])

## 1. Linear Algebra

In [91]:
a = np.ones((3,3))
b = np.full((3,3),3)
print(a)
print(b)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[3 3 3]
 [3 3 3]
 [3 3 3]]


In [92]:
#matrix  multiplication
np.matmul(a,b)

array([[9., 9., 9.],
       [9., 9., 9.],
       [9., 9., 9.]])

In [94]:
# Find the determinant of the matrix
c= np.identity(3)
np.linalg.det(c)

1.0

In [95]:
# find out many more at numpy docs 

## 2. Statistics

In [97]:
stats = np.array([[1,2,3],[11,22,33]])
stats

array([[ 1,  2,  3],
       [11, 22, 33]])

In [103]:
#Find minimum
np.min(stats, axis=1)

array([ 1, 11])

In [101]:
#Find maximum
np.max(stats)

33

In [105]:
np.sum(stats, axis=0)

array([12, 24, 36])

## 3. Organizing arrays

In [113]:
# Reshaping the aaray elements
bef = np.array([[1,2,3],[11,22,33],[111,222,333]])
print("BEFORE -->", bef)

after = bef.reshape((1,9))
print("AFTER -->", after)

BEFORE --> [[  1   2   3]
 [ 11  22  33]
 [111 222 333]]
AFTER --> [[  1   2   3  11  22  33 111 222 333]]


In [121]:
#Vertically stacking array (should be of same dimension tho)
a = np.array([1,2,3,4])
b = np.array([6,7,8,9])

np.vstack([a,b,a])

array([[1, 2, 3, 4],
       [6, 7, 8, 9],
       [1, 2, 3, 4]])

In [124]:
#Horizontal stacking array (should be of same dimension tho)
a = np.array([1,2,3,4])
b = np.array([6,7,8,9])

np.hstack((a,b))

array([1, 2, 3, 4, 6, 7, 8, 9])

# Miscellaneous

## 1. Loading Data from text file

In [3]:
fd = np.genfromtxt('npData.txt', delimiter=',')
fd = fd.astype('int32')
fd

array([[  1,   2,   3,   4,   5,   6,   7],
       [ 11,  22,  33,  44,  55,  66,  77],
       [111, 222, 333, 444, 555, 666, 777]])

## 2. Boolean Masking and Advanced Indexing

In [7]:
# an array marked as boolean value based on the condition
print("Values which are greater than 20 in the file data-->",'\n',fd>20)

Values which are greater than 20 in the file data--> 
 [[False False False False False False False]
 [False  True  True  True  True  True  True]
 [ True  True  True  True  True  True  True]]


In [15]:
#checks if any value in any column is greater than 40
#keep axis=1 if you wanna check it row wise
np.any(fd>40, axis=0)

array([ True,  True,  True,  True,  True,  True,  True])

In [20]:
#checks if all the value in any column is greater than 40
#keep axis=1 if you wanna check it row wise
np.all(fd>40, axis=1)

array([False, False,  True])

In [8]:
#Getting the values which are satisfying the conditions
fd[fd>23]

array([ 33,  44,  55,  66,  77, 111, 222, 333, 444, 555, 666, 777])

In [10]:
#Indexing with a list in NumPy
a=np.array([1,2,3,4,5,6,7,8,9])
a[[2,4,6,7]]


array([3, 5, 7, 8])

# Practice

In [25]:
arr = np.arange(1,31)
arr.reshape(6,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])